### ISSUE TITLE
all your java project can not run for gradle

### ISSUE THREAD

**Issue by dawnFromDark** [EOSIO/eosio-java-softkey-signature-provider#36]
as mentioned in topic,the project can not run ,may you fix it?

Could not get unknown property 'artifactory_username' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.

**Comment by GonnaGitYou** [comment]
Thank you for the feedback.  We have updated the Readme under the Installation section to let you and other developers know how to remove the Artifactory configurations that are causing the build errors you are seeing.  Please go to the build.gradle files at the project and module levels and follow the instructions in the added comments.  They show you which lines to delete if you are not using Artifactory.  Please let us know if you find any other issues and thank you for your contributions.

**Comment by dawnFromDark** [comment]
> Thank you for the feedback. We have updated the Readme under the Installation section to let you and other developers know how to remove the Artifactory configurations that are causing the build errors you are seeing. Please go to the build.gradle files at the project and module levels and follow the instructions in the added comments. They show you which lines to delete if you are not using Artifactory. Please let us know if you find any other issues and thank you for your contributions.

it works ,thanks for help..
